services:
  mysql:
    image: 'mysql'
    environment:
      - 'MYSQL_DATABASE=CoursesCRUD'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'