services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: coursescrud
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: dockerfile-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: dockerfile-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  db-data: 
    driver: local